root: true
env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:vue/strongly-recommended
parser: vue-eslint-parser
parserOptions:
  ecmaVersion: latest
  sourceType: module
  ecmaFeatures:
    jsx: true
  vueFeatures:
    filter: true
    interpolationAsNonHTML: false

globals:
  defineEmits: readonly
  defineExpose: readonly
  defineProps: readonly
  defineOptions: readonly
  JSX: readonly

plugins:
  - 'vue'
  - prettier

ignorePatterns:
  - 'node_modules/**/*'
  # Build result
  - '/dist/**/*'
  - '**/unpackage/**/*'
  - '.vscode/**/*'
rules:
  indent: off
  linebreak-style:
    - error
    - unix
  eqeqeq:
    - error
    - always
  quotes:
    - error
    - single
  semi:
    - error
    - never
  comma-dangle:
    - error
    - always-multiline
  no-mixed-spaces-and-tabs:
    - error
    - smart-tabs
  no-unused-vars: error

  vue/max-attributes-per-line:
    - error
    - singleline: 4
      multiline: 1
  vue/html-indent:
    - error
    - 2
  vue/multi-word-component-names:
    - warn
    - always
  vue/no-v-for-template-key: off
  vue/no-v-for-template-key-on-child: error
  vue/html-self-closing:
    - warn
    - html:
        void: any

  # component name casing
  vue/component-name-in-template-casing:
    - error
    - kebab-case
    - registeredComponentsOnly: false
  vue/component-options-name-casing:
    - error
    - 'PascalCase'
  vue/custom-event-name-casing:
    - error
    - 'camelCase'

  prettier/prettier: error

  import/no-unresolved: error
  import/order:
    - error
    - groups: ['builtin', 'external', 'internal', 'unknown', 'parent', 'sibling', 'index', 'object', 'type']
      newlines-between: always
      alphabetize:
        order: asc
        caseInsensitive: false

overrides:
  - files:
      - '**/*.vue'
    globals:
      defineProps: readonly
      defineEmits: readonly
      defineExpose: readonly
