root: true
env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - 'plugin:@typescript-eslint/recommended'
  - plugin:vue/strongly-recommended
parser: vue-eslint-parser
parserOptions:
  ecmaVersion: latest
  sourceType: module
  parser: '@typescript-eslint/parser'
  ecmaFeatures:
    jsx: true
    tsx: true
  vueFeatures:
    filter: true
    interpolationAsNonHTML: false
settings:
  import/resolver:
    typescript: true
    node: true
globals:
  defineEmits: readonly
  defineExpose: readonly
  defineProps: readonly
  defineOptions: readonly
  JSX: readonly

plugins:
  - '@typescript-eslint'
  - 'vue'
  - prettier
ignorePatterns:
  - 'node_modules/**/*'
  # Build result
  - '/dist/**/*'
  - '**/unpackage/**/*'
  - '.vscode/**/*'
rules:
  indent: off
  linebreak-style:
    - error
    - unix
  eqeqeq:
    - error
    - always
  quotes:
    - error
    - single
  semi:
    - error
    - never
  comma-dangle:
    - error
    - always-multiline
  no-mixed-spaces-and-tabs:
    - error
    - smart-tabs
  no-unused-vars: off
  '@typescript-eslint/no-unused-vars':
    - error
    - argsIgnorePattern: '^_'
      varsIgnorePattern: '^_'

  # Not intended but it is easier for api requesting
  '@typescript-eslint/no-explicit-any': off

  vue/max-attributes-per-line: off
  vue/html-indent: off
  vue/multi-word-component-names: off
  vue/singleline-html-element-content-newline: off
  vue/no-v-for-template-key: off
  vue/no-v-for-template-key-on-child: error
  vue/html-self-closing:
    - warn
    - html:
        void: any

  prettier/prettier: error

  # TypeScript would do the checking
  import/no-unresolved: off
  import/order:
    - error
    - groups: ['builtin', 'external', 'internal', 'unknown', 'parent', 'sibling', 'index', 'object', 'type']
      newlines-between: always
      alphabetize:
        order: asc
        caseInsensitive: false

overrides:
  - files:
      - '**/*.ts'
    rules:
      '@typescript-eslint/no-unused-vars':
        - error
        - argsIgnorePattern: '^_'
          varsIgnorePattern: '^_'
      '@typescript-eslint/no-namespace': off

  - files:
      - '**/*.vue'
    globals:
      defineProps: readonly
      defineEmits: readonly
      defineExpose: readonly
    rules:
      '@typescript-eslint/no-unused-vars':
        - error
        # ignore variables started with '_' or exactly 'props'(used in vue)
        - varsIgnorePattern: (^_)|(^props$)
